# Generated by Django 4.2.21 on 2025-05-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_book_read_date',
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_book_review_rank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_cover_img',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
