# Generated by Django 4.2.21 on 2025-05-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_customer_review_rank',
            field=models.IntegerField(null=True),
        ),
    ]
