# Generated by Django 4.2.21 on 2025-05-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_customer_review_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
