# Generated by Django 4.2.21 on 2025-05-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_book_ranking_book_book_salespoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_salesPoint',
            new_name='book_sales_point',
        ),
    ]
