# Generated by Django 4.2.21 on 2025-05-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_book_salespoint_book_book_sales_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_sales_point',
        ),
        migrations.AddField(
            model_name='book',
            name='book_ranking',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
