# Generated by Django 4.2.21 on 2025-05-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_book_sales_point_book_book_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_customer_review_rank',
        ),
    ]
