# Generated by Django 4.2.21 on 2025-05-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_book_customer_review_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_recommened',
            field=models.BooleanField(default=False),
        ),
    ]
