# Generated by Django 4.2.21 on 2025-05-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_book_recommened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_cover_img',
            field=models.ImageField(default='\threads\thread_covers\\default_banner.png', upload_to='threads/thread_covers/'),
        ),
    ]
