# Generated by Django 4.2.21 on 2025-05-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_banner_img',
            field=models.ImageField(blank=True, default='default_banner.png', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_img',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profiles/'),
        ),
    ]
