# Generated by Django 4.2.21 on 2025-05-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_user_banner_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_banner_img',
            field=models.ImageField(blank=True, default='accounts/banners/default_banner.png', upload_to='accounts/banners/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_img',
            field=models.ImageField(blank=True, default='accounts/profiles/default_profile.png', upload_to='accounts/profiles/'),
        ),
    ]
